export { default as step1 } from './step1.png'
export { default as step2 } from './step2.png'
export { default as step3 } from './step3.png'
export { default as step4 } from './step4.png'
export { default as step5 } from './step5.png'
